### ISSUE TITLE
No deployment when changing g5k.env default parameter

### ISSUE THREAD

**Issue by walidsaad** [lnussbaum/vagrant-grid5000#12]
Vagrant works perfecly with jessie-x64-base environment. But if I change the
g5k.env parameter  wih my environment name (g5k.env = my-env), the
deployment is started and finished rapidly without exhibiting any  error
during process!!
It seems that the vagrant process is interrupted at deployment stage with
Kadeploy.
The visibility tag of my envt is shared.

Logs==>
_I, [2016-03-03 15:10:56 #11278]  INFO -- ruby-cute: Waiting for 1 deployment
I, [2016-03-03 15:11:01 #11278]  INFO -- ruby-cute: Waiting for 1 deployment
I, [2016-03-03 15:11:01 #11278]  INFO -- ruby-cute: Waiting for 1 deployment
I, [2016-03-03 15:11:05 #11278]  INFO -- ruby-cute: Deployment finished
==> smaster: Node sagittaire-43.lyon.grid5000.fr successfully started.
I, [2016-03-03 15:11:05 #11278]  INFO -- ruby-cute: Deployment finished
==> node_1: Node sagittaire-55.lyon.grid5000.fr successfully started._

**Comment by camilo1729** [comment]
vagrant-grid5000 carries out the deployment using the G5K API. In order to deploy a customized environment using the G5K API, you have to put an image that is accessible through HTTP in the environment description. For example:

``` yaml
---
name: jessie-dpdk
version: 2
description: Debian 8
author: cristian.ruiz@inria.fr
visibility: shared
destructive: false
os: linux
image:
  file: http://public.nancy.grid5000.fr/~cruizsanabria/jessie-ovsdpdk.tgz
  kind: tar
  compression: gzip
postinstalls:
- archive: server:///grid5000/postinstalls/debian-x64-nfs-2.6-post.tgz
  compression: gzip
  script: traitement.ash /rambin
boot:
  kernel: "/vmlinuz"
  initrd: "/initrd.img"
  kernel_params: intel_idle.max_cstate=0 intel_pstate=disable init=/bin/systemd
filesystem: ext4
partition_type: 131
multipart: false
```

So, make sure that `file` in the image section points to a file that is accessible through HTTP
